image: azul/zulu-openjdk:8

stages:
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  tags:
    - corda
  stage: build
  script:
    - ./gradlew clean test --info
  artifacts:
    when: on_failure
    paths:
      - workflows/build/reports
    expire_in: 30 days
    reports:
        junit: build/test-results/test/**/TEST-*.xml
deploySingleNode:
  tags:
    - corda
  stage: deploy
  script:
    - ./gradlew deploySingleNode
  artifacts:
    paths:
      - corda/cordformation/build/nodes/SingleNode_SN/cordapps
      - corda/cordformation/build/nodes/SingleNode_SN/corda.jar
    expire_in: 30 days

bootJar:
  tags:
    - corda
  stage: deploy
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - api/build/libs/api.jar
    expire_in: 30 days