image: azul/zulu-openjdk:8

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

contract_and_flow_test:
  tags:
    - corda
  stage: test
  script:
    - ./gradlew clean test
  artifacts:
    paths:
      - builds/gitlab/semantic-ledger-technology/platform-corda/workflows/build/reports/tests/test/index.html
    expire_in: 1 month

build-l0:
  tags:
    - corda
  stage: build
  script:
    - ./gradlew deployNodes
  artifacts:
    paths: 
      - build/nodes
    expire_in: 1 week

deploy_sensorlab_1:
  stage: deploy
  script:
    - echo "Deploy first node to sensorlab"
  environment:
    name: sensorlab_1
    url: https://federated.sensorlab.tno.nl
