image: azul/zulu-openjdk:8

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

contract_and_flow_test:
  tags:
    - corda
  stage: test
  script:
    - ./gradlew clean test
  artifacts:
    when: on_failure
    paths:
      - workflows/build/reports
    expire_in: 30 days

build-l0:
  tags:
    - corda
  stage: build
  script:
    - ./gradlew deploySingleNode
  artifacts:
    paths: 
      - build/nodes/SingleNode_SN/cordapps
      - build/nodes/SingleNode_SN/corda.jar
    expire_in: 30 days

build-l1:
  tags:
    - corda
  stage: build
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - clients/build/libs/clients-0.1.jar
    expire_in: 30 days

deploy_sensorlab_1:
  tags:
    - corda
  stage: deploy
  script:
    - echo "Deploy first node to sensorlab"
  environment:
    name: sensorlab_1
    url: https://federated.sensorlab.tno.nl
