stages:
  - build
  - test
  - deploy

contract_and_flow_test:
  tags:
    - corda
  stage: test
  image: azul/zulu-openjdk:8
  script:
    - ./gradlew clean test

build-l0:
  tags:
    - corda
  stage: build
  image: azul/zulu-openjdk:8
  script:
    - ./gradlew deployNodes
  artifacts:
    paths: 
      - build/nodes
    expire_in: 1 week

deploy_sensorlab_1:
  stage: deploy
  script:
    - echo "Deploy first node to sensorlab"
  environment:
    name: sensorlab_1
    url: https://federated.sensorlab.tno.nl
