partya-registration:
  image: corda/corda-zulu-java1.8-4.5.8:latest
  environment:
    CORDA_ARGS: --initial-registration --network-root-truststore /tmp/network-truststore.jks --network-root-truststore-password trustpass
  container_name: partya
  ports:
    - "10006:10006"
    - "10005:10005"
  volumes:
    - ./partya/node.conf:/etc/corda/node.conf
    - ./partya/certificates:/opt/corda/certificates
    - ./shared/network-truststore.jks:/tmp/network-truststore.jks
partya:
  image: corda/corda-zulu-java1.8-4.5.8:latest
  container_name: partya
  ports:
    - "10006:10006"
    - "10005:10005"
  volumes:
    - ./partya/node.conf:/etc/corda/node.conf
    - ./partya/certificates:/opt/corda/certificates
    - ./shared/cordapps:/opt/corda/cordapps
    - ./shared/network-truststore.jks:/tmp/network-truststore.jks