version: '3.9'
#
# For more info see: https://github.com/khaller93/graphdb-free
#
# If on Windows WSL2 the mounting of the volume does not work, make sure to check that in your Windows home dir .wslconfig the following option is set:
#
#  [automount]
#  options = "metadata"
#
# Note: remove the graphdb-data/<repo>/init.lock if you want to reinitialize the graphdb repository.
#
services:
    graphdb:
        volumes:
            - './graphdb/repositories:/repository.init'
        ports:
            - '7200:7200'
        image: 'khaller/graphdb-free:10.6.2'
        container_name: graphdb

    graphdb_nl:
        volumes:
            - './graphdb/repositories:/repository.init'
        ports:
            - '7201:7200'
        image: 'khaller/graphdb-free:10.6.2'
        container_name: graphdb_nl

    graphdb_de:
        volumes:
            - './graphdb/repositories:/repository.init'
        ports:
            - '7202:7200'
        image: 'khaller/graphdb-free:10.6.2'
        container_name: graphdb_de

    graphdb_gb:
        volumes:
            - './graphdb/repositories:/repository.init'
        ports:
            - '7203:7200'
        image: 'khaller/graphdb-free:10.6.2'
        container_name: graphdb_gb