version: '3.9'

services:
    graphdb:
        volumes:
            - 'graphdb-data:/opt/graphdb/data'
        ports:
            - '7200:7200'
        image: 'khaller/graphdb-free:10.0.0'
        container_name: graphdb
    semanticadapter:
        ports:
            - '1337:1337'
        image: 'tystnad/semantic-adapter:tl-0.5'
        container_name: semanticadapter

volumes:
    graphdb-data: