version: '3.3'
services:
  corda-zulu-java1.8-4.5:
    volumes:
      - '.:/etc/corda'
      - './certificates:/opt/corda/certificates'
      - '.:/opt/corda/persistence'
      - './logs:/opt/corda/logs'
      - './cordapps:/opt/corda/cordapps'
      - './additional-node-infos:/opt/corda/additional-node-infos'
      - './network-parameters:/opt/corda/network-parameters'
    ports:
      - '10006:10006'
      - '10005:10005'
    image: 'corda/corda-zulu-java1.8-4.5.8:latest'