# This compose file is meant to be used in the appropriate repository
# TNO internal: https://ci.tno.nl/gitlab/semantic-ledger-technology/docker-bdi-node
# Publicly available: https://github.com/Federated-BDI/Docker-BDI-Node

version: '3.9'
services:
  corda-registration:
    environment:
      CORDA_ARGS: --initial-registration --network-root-truststore /tmp/network-truststore.jks --network-root-truststore-password trustpass
    volumes:
      - './certificates:/opt/corda/certificates'
      - './node.conf:/etc/corda/node.conf'
      - './network-truststore.jks:/tmp/network-truststore.jks'
    ports:
      - '10006:10006'
      - '10005:10005'
    container_name: corda-BDI-node-registration
    image: 'corda/corda-zulu-java1.8-4.5.8:latest'
    profiles:
      - registration
    networks:
      - BDI-node-net
      
  corda:
    volumes:
      - './certificates:/opt/corda/certificates'
      - './node.conf:/etc/corda/node.conf'
      - './network-truststore.jks:/tmp/network-truststore.jks'
      - './cordapps:/opt/corda/cordapps'
      - './database.properties:/opt/corda/database.properties'
    ports:
      - '10006:10006'
      - '10005:10005'
    container_name: corda-BDI-node
    image: 'corda/corda-zulu-java1.8-4.5.8:latest'
    profiles:
      - run
    networks:
      - BDI-node-net

  spring:
    environment:
      cordaHost: "corda"
      cordaPort: 10006
      cordaUser: "user1"
      cordaPassword: "vzzuABeCut3jGoJfEp94"
      springPort: 10050
    ports:
      - '10050:10050'
    depends_on:
      - corda
    image: 'andreasdog/corda-client-springboot:0.1.0'
    container_name: spring-API
    profiles:
      - run
    # volumes:
    #   - './log-client.txt:/log-client.txt'
    networks:
      - BDI-node-net
    restart: on-failure

  graphdb:
    volumes:
      - './graphdb-data:/opt/graphdb/data'
    ports:
      - '7200:7200'
    image: 'khaller/graphdb-free:9.8.0'
    container_name: graphdb
    profiles:
      - run
    networks:
      - BDI-node-net

networks:
  BDI-node-net: {}
