openapi: 3.0.0
info:
  title: Open API Merger
  description: All files merged by open api merger
  license:
    name: Apache License v2.0
    url: https://apache.org/v2
  version: 1.0.0-SNAPSHOT
servers:
- url: /
paths:
  /ArrivalEvent:
    post:
      summary: Create a resource of type ArrivalEvent.
      description: Create a resource of type ArrivalEvent.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArrivalEvent'
        required: true
      responses:
        "200":
          description: Successfully created the resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrivalEvent'
        "400":
          description: Bad Request
        "401":
          description: Unauthorised
        "415":
          description: Unsupported Media Type
  /ArrivalEvent/{resourceId}:
    get:
      summary: Retrieve a resource of type ArrivalEvent by id.
      description: Retrieve a resource of type ArrivalEvent by id.
      parameters:
      - name: resourceId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorised
        "404":
          description: Resource not found
        "415":
          description: Unsupported Media Type
  /LoadEvent:
    post:
      summary: Create a resource of type LoadEvent.
      description: Create a resource of type LoadEvent.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoadEvent'
        required: true
      responses:
        "200":
          description: Successfully created the resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoadEvent'
        "400":
          description: Bad Request
        "401":
          description: Unauthorised
        "415":
          description: Unsupported Media Type
  /LoadEvent/{resourceId}:
    get:
      summary: Retrieve a resource of type LoadEvent by id.
      description: Retrieve a resource of type LoadEvent by id.
      parameters:
      - name: resourceId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorised
        "404":
          description: Resource not found
        "415":
          description: Unsupported Media Type
components:
  schemas:
    Actor:
      title: 'Actor in the business transaction '
      required:
      - actorLegalPerson
      - actorLogisticsRole
      type: object
      properties:
        actorLegalPerson:
          minItems: 1
          type: array
          items:
            required:
            - legalPersonAddress
            - legalPersonID
            - legalPersonName
            type: object
            properties:
              legalPersonAddress:
                minItems: 1
                type: array
                items:
                  required:
                  - locatedAtStreetName
                  - locatedInCity
                  - locatedInCountry
                  - postalAddress
                  - postalCode
                  type: object
                  properties:
                    postalCode:
                      minItems: 1
                      type: array
                      items:
                        type: string
                    locatedAtStreetName:
                      minItems: 1
                      type: array
                      items:
                        type: string
                    postalAddress:
                      minItems: 1
                      type: array
                      items:
                        type: string
                    locatedInCountry:
                      minItems: 1
                      type: array
                      items:
                        required:
                        - countryISOCode
                        type: object
                        properties:
                          countryISOCode:
                            minItems: 1
                            type: array
                            items:
                              type: object
                        additionalProperties: false
                    locatedInCity:
                      minItems: 1
                      type: array
                      items:
                        required:
                        - cityName
                        type: object
                        properties:
                          cityName:
                            minItems: 1
                            type: array
                            items:
                              type: string
                        additionalProperties: false
                  additionalProperties: false
              legalPersonName:
                minItems: 1
                type: array
                items:
                  type: string
              legalPersonID:
                minItems: 1
                type: array
                items:
                  type: string
            additionalProperties: false
        actorLogisticsRole:
          minItems: 1
          type: array
          items:
            type: string
            enum:
            - Consignee
            - Consignor
            - Carrier
      additionalProperties: false
      description: "Actor has a role and is described by a legal person - relevant\
        \ for us: consignor, consignee, carrier"
    ArrivalEvent:
      title: ArrivalEvent version undefined
      required:
      - involvesActor
      - involvesDigitalTwin
      type: object
      properties:
        involvesActor:
          type: array
          items:
            $ref: '#/components/schemas/Actor'
        involvesDigitalTwin:
          type: array
          items:
            $ref: '#/components/schemas/TransportMeans'
      additionalProperties: false
      description: Generated by TNO FEDeRATED
    DangerousGoods:
      title: Dangerous goods
      required:
      - UNDGCode
      - dangerousGoodsEMSID
      - dangerousGoodsFlashpointTemperature
      - dangerousGoodsHazardClassificationID
      - dangerousGoodsPackagingDangerLevelCode
      - dangerousGoodsProperShippingName
      - dangerousGoodsRegulationCode
      - dangerousGoodsSupplementaryInformation
      - dangerousGoodsTechnicalName
      - grossMass
      - grossVolume
      description: "Specialized cargo, dangerous goods"
      allOf:
      - $ref: '#/components/schemas/DigitalTwin'
      - type: object
        properties:
          grossMass:
            type: string
          grossVolume:
            type: string
          UNDGCode:
            type: string
          dangerousGoodsRegulationCode:
            type: string
          dangerousGoodsTechnicalName:
            type: string
          dangerousGoodsEMSID:
            type: string
          dangerousGoodsPackagingDangerLevelCode:
            type: string
          dangerousGoodsHazardClassificationID:
            type: string
          dangerousGoodsProperShippingName:
            type: string
          dangerousGoodsSupplementaryInformation:
            type: string
          dangerousGoodsFlashpointTemperature:
            type: string
    DigitalTwin:
      title: A digital twin
      required:
      - digitalTwinType
      properties:
        digitalTwinType:
          type: string
        digitalTwinID:
          type: string
      description: "May represent a transport means, a transport equipment or cargo\
        \ (goods / dangerous goods)"
    Goods:
      title: Goods
      required:
      - goodsDescription
      - goodsTypeCode
      - grossMass
      - grossVolume
      - netMass
      - numberOfUnits
      description: "Specialized cargo, goods"
      allOf:
      - $ref: '#/components/schemas/DigitalTwin'
      - type: object
        properties:
          grossMass:
            type: string
          grossVolume:
            type: string
          goodsTypeCode:
            type: string
          netMass:
            type: integer
          numberOfUnits:
            type: integer
          goodsDescription:
            type: string
    LoadEvent:
      title: Load Event version 1
      required:
      - involvesActor
      - involvesDigitalTwin1
      - involvesDigitalTwin2
      type: object
      properties:
        involvesActor:
          $ref: '#/components/schemas/Actor'
        involvesDigitalTwin1:
          discriminator:
            propertyName: digitalTwinType
          oneOf:
          - $ref: '#/components/schemas/TransportMeans'
          - $ref: '#/components/schemas/TransportEquipment'
          - $ref: '#/components/schemas/DangerousGoods'
          - $ref: '#/components/schemas/Goods'
        involvesDigitalTwin2:
          discriminator:
            propertyName: digitalTwinType
          oneOf:
          - $ref: '#/components/schemas/TransportMeans'
          - $ref: '#/components/schemas/TransportEquipment'
          - $ref: '#/components/schemas/DangerousGoods'
          - $ref: '#/components/schemas/Goods'
      additionalProperties: false
      description: Generated by TNO FEDeRATED
    TransportEquipment:
      title: Transport equipment
      required:
      - grossMass
      - grossVolume
      - size
      - transportEquipmentSizeType
      additionalProperties: false
      description: Equipment to be used for transport of goods
      allOf:
      - $ref: '#/components/schemas/DigitalTwin'
      - type: object
        properties:
          grossMass:
            type: string
          grossVolume:
            type: string
          transportEquipmentSizeType:
            type: string
            enum:
            - AA
            - AB
            - AC
            - AD
            - AE
            - AF
            - AG
            - AH
            - AI
            - AJ
            - AK
            - AL
            - AM
            - AN
            - AO
            - AP
            - AQ
            - AR
            - AS
            - AT
            - AU
            - AV
            - AX
            - AY
            - AZ
            - BA
            - BB
            - BC
            - BD
            - BE
            - BF
            - BG
            - BH
            - BI
            - BJ
            - BK
            - BL
            - BM
            - BN
            - BO
            - BP
            - BR
          size:
            type: string
    TransportMeans:
      title: Transport means
      required:
      - transportMeansMode
      - transportMeansNationality
      additionalProperties: false
      description: "Specialized digital twin, mostly truck"
      allOf:
      - $ref: '#/components/schemas/DigitalTwin'
      - type: object
        properties:
          transportMeansMode:
            type: string
            enum:
            - Sea
            - Rail
            - Road
            - Air
            - Mail
            - Multimodal
            - Pipelines
            - InlandWaterways
          hasTransportmeansNationality:
            type: string
            enum:
            - AD
            - AE
            - AF
            - AG
            - AI
            - AL
            - AM
            - AO
            - AQ
            - AR
            - AS
            - AT
            - AU
            - AW
            - AX
            - AZ
            - BA
            - BB
            - BD
            - BE
            - BF
            - BG
            - BH
            - BI
            - BJ
            - BL
            - BM
            - BN
            - BO
            - BQ
            - BR
            - BS
            - BT
            - BW
            - BY
            - BZ
            - CA
            - CC
            - CD
            - CF
            - CG
            - CH
            - CI
            - CK
            - CL
            - CM
            - CN
            - CO
            - CR
            - CU
            - CVCW
            - CX
            - CY
            - CZ
            - DE
            - DJ
            - DK
            - DM
            - DO
            - DZ
            - EC
            - EE
            - EG
            - EH
            - ER
            - ES
            - ET
            - FI
            - FJ
            - FK
            - FM
            - FO
            - FR
            - GA
            - GB
            - GD
            - GE
            - GF
            - GG
            - GH
            - GI
            - GL
            - GM
            - GN
            - GP
            - GQ
            - GR
            - GS
            - GT
            - GU
            - GW
            - GY
            - HK
            - HM
            - HN
            - HR
            - HT
            - HU
            - ID
            - IE
            - IL
            - IM
            - IN
            - IO
            - IQ
            - IR
            - IS
            - IT
            - JE
            - JM
            - JO
            - JP
            - KE
            - KG
            - KH
            - KI
            - KM
            - KN
            - KP
            - KR
            - KW
            - KY
            - KZ
            - LA
            - LB
            - LC
            - LI
            - LK
            - LR
            - LS
            - LT
            - LU
            - LV
            - LY
            - MA
            - MC
            - MD
            - ME
            - MF
            - MG
            - MH
            - MK
            - ML
            - MM
            - MN
            - MO
            - MP
            - MQ
            - MR
            - MS
            - MT
            - MU
            - MV
            - MW
            - MX
            - MY
            - MZ
            - NC
            - NE
            - NF
            - NG
            - NI
            - NL
            - "false"
            - NP
            - NR
            - NU
            - NZ
            - OM
            - PA
            - PE
            - PF
            - PG
            - PH
            - PK
            - PL
            - PM
            - PN
            - PR
            - PS
            - PT
            - PW
            - PY
            - QA
            - RE
            - RO
            - RS
            - RU
            - RW
            - SA
            - SB
            - SC
            - SD
            - SE
            - SG
            - SH
            - SI
            - SJ
            - SK
            - SL
            - SM
            - SN
            - SO
            - SR
            - SS
            - ST
            - SV
            - SX
            - SY
            - SZ
            - TC
            - TD
            - TF
            - TG
            - TH
            - TJ
            - TK
            - TL
            - TM
            - TN
            - TO
            - TR
            - TT
            - TV
            - TW
            - TZ
            - UA
            - UG
            - UM
            - US
            - UY
            - UZ
            - VA
            - VC
            - VE
            - VG
            - VI
            - VN
            - VU
            - WF
            - WS
            - XZ
            - YE
            - YT
            - ZA
            - ZM
            - ZW
